"""
In-memory one-time token store shared between the bot and the API.
Tokens are generated by the bot (/webadmin command) and consumed by the API (/auth/token-login).
"""
import secrets
import time

# { token: (admin_id, expires_at) }
_store: dict[str, tuple[int, float]] = {}

TOKEN_TTL = 300  # 5 minutes


def create(admin_id: int) -> str:
    token = secrets.token_urlsafe(32)
    _store[token] = (admin_id, time.time() + TOKEN_TTL)
    return token


def consume(token: str) -> int | None:
    """Validate and remove token. Returns admin_id or None."""
    entry = _store.pop(token, None)
    if not entry:
        return None
    admin_id, expires_at = entry
    if time.time() > expires_at:
        return None
    return admin_id


def cleanup() -> None:
    """Remove expired tokens (call periodically if needed)."""
    now = time.time()
    expired = [t for t, (_, exp) in _store.items() if now > exp]
    for t in expired:
        _store.pop(t, None)
